### ISSUE TITLE
Domain Credentail is not working (client outside the domain)

### ISSUE THREAD

**Issue by felipericcetto** [cloudsoft/winrm4j#37] opened 2016-08-04 20:54 UTC
Hi,
I am trying to connect to a windows 2008 server and my workstation is NOT on the domain.
I am getting the error.

When using KERBEROS:

```
System.setProperty("java.security.auth.login.config", "login.conf");
        System.setProperty("java.security.krb5.conf", "krb5.conf");
        System.setProperty("sun.security.krb5.debug", "true");
        System.setProperty("javax.security.auth.useSubjectCredsOnly", "false");

        WinRmTool.Builder builder = WinRmTool.Builder.builder(
                "myserver.com", "NAME_OF_MY_DOMAIN", "NAME_OF_MY_USER",
                "MY_PASSWORD");

        builder.disableCertificateChecks(true);
        builder.setAuthenticationScheme(AuthSchemes.KERBEROS);
        builder.port(WinRmTool.DEFAULT_WINRM_HTTPS_PORT);
        builder.useHttps(true);
        WinRmTool tool = builder.build();
        WinRmToolResponse result = tool.executeCommand("echo aaa");
        System.out.println(result.getStdOut());
        System.err.println(result.getStdErr());

```

I get the error:

> Using builtin default etypes for default_tkt_enctypes
> default etypes for default_tkt_enctypes: 17 16 23 1 3.
> 
> > > KrbAsReq creating message
> > > KrbKdcReq send: kdc=myserver.com TCP:88, timeout=30000, number of retries =3, #bytes=150
> > > KrbKdcReq send: error trying myserver.com
> > > java.net.ConnectException: Connection refused: connect

---

When I try with NTLM:

```
WinRmTool.Builder builder = WinRmTool.Builder.builder(
                "myserver.com", "NAME_OF_MY_DOMAIN", "NAME_OF_MY_USER",
                "MY_PASSWORD");

        builder.disableCertificateChecks(true);
        builder.setAuthenticationScheme(AuthSchemes.NTLM);
        builder.port(WinRmTool.DEFAULT_WINRM_HTTPS_PORT);
        builder.useHttps(true);
        WinRmTool tool = builder.build();
        WinRmToolResponse result = tool.executeCommand("echo aaa");
        System.out.println(result.getStdOut());
        System.err.println(result.getStdErr());
```

I get the error:

> Caused by: org.apache.cxf.binding.soap.SoapFault: Access is denied. 

Im my workstation, when I run the commands below in the PowerSheel, works fine:

$so = New-PsSessionOption -SkipCACheck -SkipRevocationCheck
etsn -cn myserver.com -Credential MY_DOMAIN\MY_USER -Authentication Negotiate -UseSSL -SessionOption $so

Any help will be appreciated.
Thanks

**Comment by neykov** [comment] 2017-03-07 16:40
Closing as a duplicate of #27. This is still useful information though so cross-referencing. @felipericcetto have you tried any of the steps in #27?

**Closed by neykov** 2017-03-07 16:40 UTC
Labels: duplicate

**Comment by techdinesh** [comment] 2020-01-06 10:16
Hi @neykov ,
I am working below snippet of code, which is working in local windows machine when I am deploying in Linux server machine remotely the same code snippet is not working 

Ex :1 

```
WinRmTool.Builder builder = WinRmTool.Builder.builder(
                "myserver.com", "NAME_OF_MY_DOMAIN", "NAME_OF_MY_USER",
                "MY_PASSWORD");

        builder.disableCertificateChecks(true);
        builder.setAuthenticationScheme(AuthSchemes.NTLM);
        builder.port(WinRmTool.DEFAULT_WINRM_HTTPS_PORT);
        builder.useHttps(false);
        WinRmTool tool = builder.build();
        WinRmToolResponse result = tool.executeCommand("echo aaa");
```
Error Message 
-----------------------------------------------------------------------------------------------------------
```
java.lang.RuntimeException: failed task create at io.cloudsoft.winrm4j.client.RetryingProxyHandler.invokeWithRetry(RetryingProxyHandler.java:67)

Caused by: javax.xml.ws.WebServiceException: Could not send Message.

org.apache.cxf.transport.http.HTTPException: HTTP response '404: Not Found' when communicating with http://myserver.com:5985/wsman
```
------------------------------------------------------------------------------------------------------------

Ex 2: Even we tried   builder.useHttps(true);

Error Message 
------------------------------------------------------------------------------------------------------------
```

Caused by: javax.xml.ws.WebServiceException: Could not send Message.
	at org.apache.cxf.jaxws.JaxWsClientProxy.mapException(JaxWsClientProxy.java:183)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:145)
	at com.sun.proxy.$Proxy136.create(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.cloudsoft.winrm4j.client.RetryingProxyHandler.invokeWithRetry(RetryingProxyHandler.java:44)
	... 58 more
Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '403: Forbidden' when communicating with https://myserver.com:5985/wsman
```
--------------------------------------------------------------------------------------------------------------

please help and advice.

Thanks,
Dinesh

**Comment by neykov** [comment] 2020-01-07 14:28
@techdinesh make sure your windows host is configured properly. Run `winrm get winrm/config/service` on the windows machine and check that you have `Negotiate` auth enabled.

Seems your problem is not related to this issue, so if you have further problems please open a separate issue.
